### ISSUE TITLE
Replace setCallback with onOpen() onClose() type of methods

### ISSUE THREAD

**Issue by MegaCrafter** [FabulousProject/FabulousCore#4]
It would be better to use seperated methods for callbacks since this will allow for lambdas.

**Comment by Alpho320** [comment]
Yeah, you're right. i'll change the design as soon as possible. Thanks for feedback.

**Comment by Alpho320** [comment]
https://github.com/FabulousProject/FabulousCore/commit/aed01d69cf7801e2c38c9dc1373b7fb9e3af2c9a
